/**
 * File generated by:
 * https://github.com/CezaryGapinski/DistortosPinConfigGenerator
 * Copyright (C) 2017 Cezary Gapinski cezary.gapinski@gmail.com
 *
 * \file
 * \brief Declaration of LEDs for 32F429IDISCOVERY
 *
 * \author Copyright (C) 2016-2017 Kamil Szczygiel http://www.distortec.com http://www.freddiechopin.info
 *
 * \par License
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
 * distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

#ifndef SOURCE_BOARD_STM32_STM32F4_32F429IDISCOVERY_INCLUDE_DISTORTOS_BOARD_LEDS_HPP_
#define SOURCE_BOARD_STM32_STM32F4_32F429IDISCOVERY_INCLUDE_DISTORTOS_BOARD_LEDS_HPP_

#include "distortos/chip/STM32-GPIOv2.hpp"

#include <array>

namespace distortos
{

#ifdef CONFIG_BOARD_LEDS_ENABLE

namespace chip
{

class ChipOutputPin;

}	// namespace chip

#endif	// def CONFIG_BOARD_LEDS_ENABLE

namespace board
{

/*---------------------------------------------------------------------------------------------------------------------+
| led indexes
+---------------------------------------------------------------------------------------------------------------------*/
enum Leds {

#if defined(CONFIG_CHIP_STM32_GPIOV2_GPIOG_ENABLE)
	ld3LedIndex, /// index of LD3 LED (green)
#endif // def CONFIG_CHIP_STM32_GPIOV2_GPIOG_ENABLE
#if defined(CONFIG_CHIP_STM32_GPIOV2_GPIOG_ENABLE)
	ld4LedIndex, /// index of LD4 LED (red)
#endif // def CONFIG_CHIP_STM32_GPIOV2_GPIOG_ENABLE
    ldLastInSeq // last value
};

/// total number of LEDs on the board
constexpr size_t totalLeds {ldLastInSeq};

/*---------------------------------------------------------------------------------------------------------------------+
| alternative (color-based) LED indexes
+---------------------------------------------------------------------------------------------------------------------*/


#if defined(CONFIG_CHIP_STM32_GPIOV2_GPIOG_ENABLE)
/// alternative index of LD3 LED (green) 
constexpr size_t greenLedIndex {ld3LedIndex};
#endif // def CONFIG_CHIP_STM32_GPIOV2_GPIOG_ENABLE

#if defined(CONFIG_CHIP_STM32_GPIOV2_GPIOG_ENABLE)
/// alternative index of LD4 LED (red) 
constexpr size_t redLedIndex {ld4LedIndex};
#endif // def CONFIG_CHIP_STM32_GPIOV2_GPIOG_ENABLE


#ifdef CONFIG_BOARD_LEDS_ENABLE

/*---------------------------------------------------------------------------------------------------------------------+
| indexed access to LED objects
+---------------------------------------------------------------------------------------------------------------------*/

/// array with all LED objects
extern chip::ChipOutputPin leds[totalLeds];

#endif	// def CONFIG_BOARD_LEDS_ENABLE

}	// namespace board

}	// namespace distortos

#endif	// SOURCE_BOARD_STM32_STM32F4_32F429IDISCOVERY_INCLUDE_DISTORTOS_BOARD_LEDS_HPP_
