/**
 * \file
 * \brief Declaration of SPIs for NUCLEO-L073RZ
 *
 * File generated by DistortosPinConfigGenerator
 * https://github.com/CezaryGapinski/DistortosPinConfigGenerator
 * \author Copyright (C) 2017 Cezary Gapinski cezary.gapinski@gmail.com
 *
 * \par License
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
 * distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 */

#include "distortos/board/spi.hpp"

#ifdef CONFIG_BOARD_SPIS_ENABLE

#include "distortos/chip/ChipOutputPin.hpp"
#include "distortos/chip/ChipAlternativePin.hpp"
#include "distortos/board/STM32-SPI-Pins.hpp"

namespace distortos
{

namespace board
{

/*---------------------------------------------------------------------------------------------------------------------+
| global objects
+---------------------------------------------------------------------------------------------------------------------*/

distortos::chip::ChipAlternativePin spi1_clk { chip::Pin::pa5,
	false,
	chip::PinOutputSpeed::veryHigh,
	chip::PinPull::up,
	chip::PinAlternateFunction::af0
};

distortos::chip::ChipAlternativePin spi1_miso { chip::Pin::pa11,
	false,
	chip::PinOutputSpeed::veryHigh,
	chip::PinPull::up,
	chip::PinAlternateFunction::af0
};
distortos::chip::ChipAlternativePin spi1_mosi { chip::Pin::pa12,
	false,
	chip::PinOutputSpeed::veryHigh,
	chip::PinPull::up,
	chip::PinAlternateFunction::af0
};
distortos::chip::ChipOutputPin spi1_cs { chip::Pin::pa4,
	false,
	chip::PinOutputSpeed::veryHigh,
	chip::PinPull::up,
	false
};

distortos::board::SpiPins spi1_pins(spi1_clk, spi1_miso, spi1_mosi, spi1_cs);


}	// namespace board

}	// namespace distortos

#endif	// def CONFIG_BOARD_SPIS_ENABLE