/**
 * \file
 * \brief Declaration of lowLevelPinInitializations for NUCLEO-L073RZ
 *
 * File generated by DistortosPinConfigGenerator
 * https://github.com/CezaryGapinski/DistortosPinConfigGenerator
 * \author Copyright (C) 2017 Cezary Gapinski cezary.gapinski@gmail.com
 *
 * \par License
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not
 * distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 *
 */

#ifndef SOURCE_BOARD_STM32_NUCLEO-L073RZ_INCLUDE_DISTORTOS_BOARD_LOW_LEVEL_PIN_INITIALIZATION_HPP_
#define SOURCE_BOARD_STM32_NUCLEO-L073RZ_INCLUDE_DISTORTOS_BOARD_LOW_LEVEL_PIN_INITIALIZATION_HPP_

namespace distortos
{

namespace board
{

void lowLevelPinInitialization();

}	// namespace board

}	// namespace distortos

#endif	// SOURCE_BOARD_STM32_NUCLEO-L073RZ_INCLUDE_DISTORTOS_BOARD_LOW_LEVEL_PIN_INITIALIZATION_HPP_